services:
  # ================================================================================
  # MONGODB CONFIGURATION (LOCAL ENV)
  # ================================================================================
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017" # Expose MongoDB default port
    networks:
      - node_network
  # ================================================================================
  # MONGODB CONFIGURATION (TEST ENV)
  # ================================================================================
  mongodb_test:
    image: mongo:latest
    container_name: mongodb-test
    ports:
      - "37017:27017" # Expose MongoDB default port
    networks:
      - node_network
  # ================================================================================
  # REDIS CONFIGURATION (LOCAL ENV)
  # ================================================================================
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379" # Expose Redis default port
    networks:
      - node_network
  # ================================================================================
  # LOCALSTACK CONFIGURATION (LOCAL ENV)
  # ================================================================================
  localstack:
    image: public.ecr.aws/localstack/localstack:latest
    container_name: craftyverse-localstack
    ports:
      - "4566:4566" # Edge port for all LocalStack services
      - "4510-4599:4510-4599" # Additional ports for services (e.g., S3)
      - "9001:9001"
    environment:
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - LAMBDA_EXECUTOR=docker
    networks:
      - node_network

  # ================================================================================
  # LOCALSTACK CONFIGURATION (LOCAL TEST INTEGRATED ENV)
  # ================================================================================
  localstack_test:
    image: public.ecr.aws/localstack/localstack:latest
    container_name: craftyverse-localstack-test
    ports:
      - "5566:4566" # Edge port for all LocalStack services
      - "5510-5599:4510-4599" # Additional ports for services (e.g., S3)
      - "9002:9001"
    environment:
      - DEBUG=1
      - DATA_DIR=/tmp/localstack-test/data
      - LAMBDA_EXECUTOR=docker
    networks:
      - node_network

  # ================================================================================
  # CRAFTYVERSE AUTH SERVICE CONFIGURATION
  # ================================================================================
  craftyverse-auth-service:
    build: ../craftyverse-auth-service
    ports:
      - "3000:3000"
    volumes:
      - ../../craftyverse-auth-service/:/usr/app
      - /usr/app/node_modules
    env_file:
      - ../craftyverse-auth-service/.env.development
    networks:
      - node_network

  # ================================================================================
  # CRAFTYVERSE MERCHANT CONFIGURATION
  # ================================================================================
  craftyverse-merchant-service:
    build: ../craftyverse-merchant-service
    ports:
      - "4000:4000"
    volumes:
      - ../../craftyverse-merchant-service/:/usr/app
      - /usr/app/node_modules
    env_file:
      - ../craftyverse-merchant-service/.env.development
    networks:
      - node_network
  # ================================================================================
  # CRAFTYVERSE USER CONFIGURATION
  # ================================================================================
  craftyverse-user-service:
    build: ../craftyverse-user-service
    ports:
      - "9000:9000"
    volumes:
      - ../../craftyverse-user-service/:/usr/app
      - /usr/app/node_modules
    env_file:
      - ../craftyverse-user-service/.env.development
    networks:
      - node_network
  # ================================================================================
  # CRAFTYVERSE DASHBOARD CONFIGURATION
  # ================================================================================
  craftyverse-dashboard:
    build: ../craftyverse-dashboard
    ports:
      - "5173:5173"
    volumes:
      - ../../craftyverse-dashboard/:/usr/app
      - /usr/app/node_modules
    env_file:
      - ../craftyverse-dashboard/.env.local
    networks:
      - node_network

networks:
  node_network:
    driver: bridge

volumes:
  localstack_data:
    driver: local
  localstack_test_data:
    driver: local
